version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prova01
      POSTGRES_DB: progetto
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend/appweb
    container_name: frontend
    ports:
    - '4200:80'

    depends_on:
      - backend

volumes:
  pgdata:
